# fzf history search
fzf-history-widget() {
  local selected num
  # Disable glob substitution, POSIX builtins, pipe failure handling, and aliases
  setopt localoptions noglobsubst noposixbuiltins pipefail no_aliases 2> /dev/null
  # `fc -rl 1` retrieves the command history from the most recent session (indicated by `-l 1`)
  # - `--height 40%` sets the height of the fzf window to 40% of the terminal's total height.
  # - `--reverse` reverses the order of the displayed history, so that the most recent commands appear at the top.
  # - `+m` ensures multi-line selection is enabled, which can be useful for longer command histories.
  # - `ctrl-r:toggle-sort` binds the Ctrl+R key to toggle between sorting the results alphabetically and by relevance (the default behavior).
  selected=( $(fc -rl 1 | fzf --height 40% --reverse --bind 'ctrl-r:toggle-sort' +m) )
  local ret=$?
  if [ -n "$selected" ]; then
    # If an entry is selected from the list generated by fzf, it is stored in the `$selected` array.
    num=$selected[1]
    if [ -n "$num" ]; then
      # Navigate directly to that command history entry within Zsh's editor mode.
      zle vi-fetch-history -n $num
    fi
  fi
  zle reset-prompt
  return $ret
}
# Bind key
zle     -N   fzf-history-widget
bindkey '^R' fzf-history-widget
